[package]
name = "phoenix-report"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
phoenix-core = { path = "../core" }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
sha2 = "0.11.0-rc.3"
zip = "7.2.0"
