[package]
name = "phoenix-wim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56", features = [
  "Win32_Foundation"
] }
