[package]
name = "phoenix-imaging"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
sha2 = "0.10"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56", features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem"
] }
